# Generated by Django 2.2.7 on 2019-11-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirreldata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='Age',
            new_name='age',
        ),
    ]
