# Generated by Django 2.2.7 on 2019-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirreldata', '0002_auto_20191130_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.CharField(help_text='(Concatenation of the sighting session month, day and year. E.g. 10142018)', max_length=8),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.CharField(help_text='(Numerical latitude value)', max_length=17),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.CharField(help_text='(Numerical longitude value)', max_length=17),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='other_activities',
            field=models.TextField(blank=True, help_text="(Activities haven't been listed. E.g. digging)", max_length=255),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='specific_location',
            field=models.TextField(blank=True, help_text='(Specific place where squirrel was sighted. E.g. crossing street)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.CharField(help_text="(Identification tag for each squirrel sightings. The tag is comprised of 'Hectare ID' + 'Shift' + 'Date(month+day)' + 'Hectare Squirrel Number'. E.g. 42C-AM-1007-02)", max_length=14, unique=True),
        ),
    ]
